name: car_rental
description: "Car rental service"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.3+1
  flutter_map: ^8.2.2
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  hooks_riverpod: ^3.0.3
  latlong2: ^0.9.1
  shared_preferences: ^2.5.3
  flutter_stripe: ^12.1.1
  http: ^1.6.0
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  build_runner: ^2.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
